name: Build and Push All-Arch to GHCR

on:
  workflow_dispatch: # 仅手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Buildx 环境
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录到 GHCR
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 构建并推送多架构镜像
    - name: Build and Push All-Arch Image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-image-name
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x,linux/386 \
          --tag $IMAGE_NAME:latest \
          --push .
